# Sum the files generated by different threads.
# xhzheng, 12/26/2014

ln=0
while read line; do
    ln=`echo $ln + 1 | bc`
    echo $ln $line;
    rm -f tmp_file1
    #for aa in `cat input`; do
    for aa in `echo $line`; do
        for i in `ls ./temp*/output/$aa.cfg`; do
            mm=`wc -l $i |awk '{print $1}'`
            nn=`head -n 1 $i|awk '{print $5}'`
            mn=`echo $mm-$nn|bc`
            #echo $mm  $nn  $mn
            tail -n $nn $i >> tmp_file1
            head -n $mn $i > head_file
        done

        sort -n -k 1 -k 2 -k 3 tmp_file1 > tmp_file2

        case "$ln" in
            "1")  # One column
            awk 'BEGIN{a=0.0; b=0.0; c=0.0; d=0.0;}
            {
                if ($1==a && $2==b && $3==c) {
                    d=d+$4;
                }
                else {
                    if (NR==1) {
                        a=$1;  b=$2;  c=$3;  d=$4;
                    }
                    else {
                        print a, b, c, d, e;
                        a=$1;  b=$2;  c=$3;  d=$4;
                    }
                }
            }
            END {print a, b, c, d}' tmp_file2 >tmp_file3
            ;;

            "2")  # Two column
            awk 'BEGIN{a=0.0; b=0.0; c=0.0; d=0.0; e=0.0;}
            {
                if ($1==a && $2==b && $3==c) {
                    d=d+$4;  e=e+$5;
                }
                else {
                    if (NR==1) {
                        a=$1;  b=$2;  c=$3;  d=$4;  e=$5;
                    }
                    else {
                        print a, b, c, d, e;
                        a=$1;  b=$2;  c=$3;  d=$4;  e=$5;
                    }
                }
            }
            END {print a, b, c, d, e}' tmp_file2 >tmp_file3
            ;;

            "3")  # Three column
            awk 'BEGIN{a=0.0; b=0.0; c=0.0; d=0.0; e=0.0; f=0.0;}
            {
                if ($1==a && $2==b && $3==c) {
                    d=d+$4;  e=e+$5;  f=f+$6;
                }
                else {
                    if (NR==1) {
                        a=$1;  b=$2;  c=$3;  d=$4;  e=$5;  f=$6;
                    }
                    else {
                        print a, b, c, d, e, f;
                        a=$1;  b=$2;  c=$3;  d=$4;  e=$5; f=$6;
                    }
                }
            }
            END {print a, b, c, d, e}' tmp_file2 >tmp_file3
        esac

        rm ./output/$aa.total.cfg
        mm=`wc -l tmp_file3 |awk '{print $1}'`
        awk '{if (NR==1) print $1,$2,$3,$4,"'$mm'"; else print $0}' head_file > ./output/$aa.total.cfg
        cat tmp_file3 >> ./output/$aa.total.cfg
    done
done < file_name

rm -rf temp*
rm -f  head_file tmp_file*
